default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_barber_db
test:
  <<: *default
  database: book_barber_db_test
production:
  <<: *default
  database: book_barber_db